# .github/workflows/get-repo-access.yml
name: Get Repository Access

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string  # This input will be in the format "owner/repository"

jobs:
  get-access:
    runs-on: ubuntu-latest

    steps:
      - name: Set repo environment variables
        run: |
          echo "GITHUB_REPOSITORY=${{ inputs.repo }}" >> $GITHUB_ENV

      - name: Checkout autograde repo
        uses: actions/checkout@v4
        with:
          repository: BZZ-Commons/repo-access-retriever
          path: repoaccessretriever
          ref: main

      - name: Get list of people with access to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}  # Use the organization-level PAT
        run: |
          python3 ./repoaccessretriever/get_repo_access.py

      - name: Set output
        id: access_list
        run: |
          echo "users=$(cat ./repoaccessretriever/access_report.txt)" >> $GITHUB_ENV

    outputs:
      users: ${{ steps.access_list.outputs.users }}
