# .github/workflows/get-repo-access.yml
name: Get Repository Access (Reusable)

on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  get-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

      - name: Get list of people with access to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT }}  # Use the organization-level PAT directly
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
        run: |
          python3 get_repo_access.py

      - name: Set output
        id: access_list
        run: |
          echo "users=$(cat access_report.txt)" >> $GITHUB_ENV

    outputs:
      users: ${{ steps.access_list.outputs.users }}
